### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Arifan** [jorticus/face-replace#2]
First of all.. Thanks for share this program..
I'm very interested on your research..
But i have a problem, when i run your program on face-replace.zip, there are few error, that program can't start because opencv_flann300.dll is missing.. What should i do?
Thanks for your concern.. ^^

**Comment by jorticus** [comment]
Zip has been updated with the missing DLLs

**Comment by Arifan** [comment]
thanks bro,
what version did you use for opencv?
because there's a lot of missing lib..
example : opencv_contrib300d.lib, etc..
